project_name: terra3

before:
  hooks:
    - go mod download
    - go generate ./...

release:
  prerelease: "false"

env:
  - CGO_ENABLED=0

builds:
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/it-objects/terra3-cli/cmd.version=v{{.Version}}
      - -s -w -X github.com/it-objects/terra3-cli/cmd.commit={{.Commit}}
      - -s -w -X github.com/it-objects/terra3-cli/cmd.date={{.Date}}

  - id: osx
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/it-objects/terra3-cli/cmd.version=v{{.Version}}
      - -s -w -X github.com/it-objects/terra3-cli/cmd.commit={{.Commit}}
      - -s -w -X github.com/it-objects/terra3-cli/cmd.date={{.Date}}

  - id: windows
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/it-objects/terra3-cli/cmd.version=v{{.Version}}
      - -s -w -X github.com/it-objects/terra3-cli/cmd.commit={{.Commit}}
      - -s -w -X github.com/it-objects/terra3-cli/cmd.date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.sha256"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: terra3
    repository:
      owner: it-objects
      name: homebrew-terra3-cli
      branch: main
    commit_author:
      name: Widura Schwittek
      email: widura.schwittek@it-objects.de
    directory: Formula
    homepage: https://terra3.io/
    description: A CLI to manage AWS deployments based on the Terra3 stack!
    license: "Apache-2.0"
    test: |
     system "terra3 version"

scoops:
  - name: terra3
    repository:
      owner: it-objects
      name: terra3-cli-dist
      branch: main
    commit_author:
      name: Widura Schwittek
      email: widura.schwittek@it-objects.de
    directory: Scoops
    homepage: https://terra3.io/
    description: A CLI to manage AWS deployments based on the Terra3 stack!
    license: "Apache-2.0"

#sboms:
#  - artifacts: archive
