project_name: terra3

before:
  hooks:
    - go mod download
    - go generate ./...

release:
  prerelease: "false"

env:
  - CGO_ENABLED=0

builds:
  - id: linux
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/it-objects/terra3-cli/cmd.version=v{{.Version}}
      - -s -w -X github.com/it-objects/terra3-cli/cmd.commit={{.Commit}}
      - -s -w -X github.com/it-objects/terra3-cli/cmd.date={{.Date}}

  - id: osx
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/it-objects/terra3-cli/cmd.version=v{{.Version}}
      - -s -w -X github.com/it-objects/terra3-cli/cmd.commit={{.Commit}}
      - -s -w -X github.com/it-objects/terra3-cli/cmd.date={{.Date}}

  - id: windows
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/derailed/k9s/cmd.version=v{{.Version}}
      - -s -w -X github.com/derailed/k9s/cmd.commit={{.Commit}}
      - -s -w -X github.com/derailed/k9s/cmd.date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.sha256"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: k9s
    repository:
      owner: it-objects
      name: homebrew-terra3-cli
    commit_author:
      name: Widura Schwittek
      email: widura.schwittek@it-objects.de
    directory: Formula
    homepage: https://terra3.io/
    description: A CLI to manage AWS deployments based on the Terr3 stack!
    test: |
      system "terra3 version"


#sboms:
#  - artifacts: archive

# chocolateys:
#   - # Your app's package name.
#     # The value may not contain spaces or character that are not valid for a URL.
#     # If you want a good separator for words, use '-', not  '.'.
#     #
#     # Default: ProjectName
#     name: terra3

#     # IDs of the archives to use.
#     # Empty means all IDs.
#     # Attention: archives must not be in the 'binary' format.
#     ids:
#       - foo
#       - bar

#     # Your chocolatey package's source URL.
#     # It point at the location of where someone can find the packaging files for the package.
#     package_source_url: https://github.com/foo/chocolatey-package

#     # Your app's owner.
#     # It basically means you.
#     owners: it-objects GmbH

#     # The app's title.
#     # A human-friendly title of the package.
#     #
#     # Default: ProjectName
#     title: Terra3 CLI

#     # Your app's authors (probably you).
#     authors: Widura Schwittek

#     # Your app's project url.
#     # It is a required field.
#     project_url: https://terra3.io/

#     # Which format to use.
#     #
#     # Valid options are:
#     # - 'msi':     msi installers (requires the MSI pipe configured, Pro only)
#     # - 'archive': archives (only if format is zip),
#     #
#     # Default: 'archive'
#     # Since: v1.24 (pro)
#     #use: msi

#     # URL which is determined by the given Token (github,
#     # gitlab or gitea).
#     #
#     # Default: depends on the git remote
#     # Templates: allowed
#     url_template: "https://github.com/it-objects/terra3-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

#     # App's icon.
#     #icon_url: "https:///icon.png"

#     # Your app's copyright details.
#     copyright: 2024 it-objects GmbH
#     # App's license information url.
#     license_url: https://github.com/it-objects/terra3-cli/blob/main/LICENSE

#     # Your apps's require license acceptance:
#     # Specify whether the client must prompt the consumer to accept the package
#     # license before installing.
#     require_license_acceptance: false

#     # Your app's source url.
#     project_source_url: github.com/it-objects/terra3-cli

#     # Your app's documentation url.
#     docs_url: github.com/it-objects/terra3-cli/blob/main/README.md

#     # App's bugtracker url.
#     bug_tracker_url: github.com/it-objects/terra3-cli/issues

#     # Your app's tag list.
#     tags: "terra3 cli AWS terraform ECS"

#     # Your app's summary:
#     summary: A CLI to manage AWS deployments based on the Terr3 stack!

#     # This the description of your chocolatey package.
#     # Supports markdown.
#     description: |
#       {{ .ProjectName }} installer package.
#       A CLI to manage AWS deployments based on the Terr3 stack!

#     # Your app's release notes.
#     # A description of the changes made in this release of the package.
#     # Supports markdown. To prevent the need to continually update this field,
#     # providing a URL to an external list of Release Notes is perfectly
#     # acceptable.
#     release_notes: "https://github.com/it-objects/terra3-cli/releases/tag/v{{ .Version }}"

#     # App's dependencies
#     # The version is not required.
#     dependencies:
#       - id: nfpm
#         version: 2.20.0

#     # The api key that should be used to push to the chocolatey repository.
#     #
#     # WARNING: do not expose your api key in the configuration file!
#     api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"

#     # The source repository that will push the package to.
#     source_repo: "https://push.chocolatey.org/"

#     # Setting this will prevent goreleaser to actually try to push the package
#     # to chocolatey repository, leaving the responsibility of publishing it to
#     # the user.
#     skip_publish: false

#     # GOAMD64 to specify which amd64 version to use if there are multiple
#     # versions from the build section.
#     #
#     # Default: 'v1'
#     goamd64: v1