name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == 'it-objects'
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - 
        name: Set up Go
        uses: actions/setup-go@v4
      - 
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v1'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_AUTH_TOKEN }}